FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=admin
ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_HOST=__REPLACE_ME__
ENV DB_POSTGRESDB_PORT=5432
ENV DB_POSTGRESDB_DATABASE=__REPLACE_ME__
ENV DB_POSTGRESDB_USER=__REPLACE_ME__
ENV DB_POSTGRESDB_PASSWORD=__REPLACE_ME__
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV GENERIC_TIMEZONE=America/Sao_Paulo